import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/app/globals.css';
import '@mantine/carousel/styles.layer.css';
import '@mantine/core/styles.layer.css';

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html
			lang='en'
			{...mantineHtmlProps}
		>
			<head>
				<ColorSchemeScript />
			</head>
			<body className={`${inter.variable} font-sans antialiased`}>
				<MantineProvider
					theme={{
						colors: {
							blue: [
								'#ebf0fe',
								'#d3dcf8',
								'#a3b6f4',
								'#708ef2',
								'#486df0',
								'#3257ef',
								'#274df0',
								'#1d3ed6',
								'#1537c0',
								'#0530ad',
							],
						},
						primaryShade: 9,
					}}
				>
					{children}
				</MantineProvider>
			</body>
		</html>
	);
};

export default RootLayout;
